### ISSUE TITLE
Freezing after fetching 50% of latest builds

### ISSUE THREAD

**Issue by scanevaro** [jhagrid77/CDDA-Ubuntu-Launcher#13]
![Screenshot from 2021-01-18 17-24-40](https://user-images.githubusercontent.com/3717246/104960328-c939ef00-59b2-11eb-8548-1b2e740af6c6.png)

Pop! OS.
i7
16gb
GTX 960m

**Comment by jhagrid77** [comment]
Hello scanevaro, 

I would love to help however, I can't say I know much about Python. I think you may have confused me for another user who forked remyroy's Python launcher ([forked project here](https://github.com/PassionateAngler/CDDA-Game-Launcher)). 

I do see that Issues are not enabled for that project, it looks like people have been commenting on the following issue on remyroy's project.
https://github.com/remyroy/CDDA-Game-Launcher/issues/329

I will be closing this issue out, as I am unable to help further.
