### ISSUE TITLE
DWM issues

### ISSUE THREAD

**Issue by joestandring** [jhagrid77/CDDA-Ubuntu-Launcher#7]
Hi, when running the script to install the tiles version on my Arch machine I get the message:
`It would appear that you do not have a graphical environment installed...`
even though I am currently using DWM and Xorg.

**Comment by jhagrid77** [comment]
Hmm, that's pretty strange. Could you do me a favor and return any output when you enter `pacman -Q | awk '{print $1}' | grep -E "xinit\|wayland"` in the terminal?

**Comment by joestandring** [comment]
That command doesnt return anything. Using `pacman -Q | awk '{print $1}' | grep -E "xinit|wayland"` returns with values containing "xinit" and "wayland" however. Changing that in the script solved it for me.

**Comment by jhagrid77** [comment]
Thank you for providing this fix, it's strange that I didn't find this issue during testing.

**Comment by joestandring** [comment]
No worries! Thanks for making playing this game on Linux much easier :)
